# Generated by Django 4.2.2 on 2023-07-25 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postinfo',
            name='height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='width',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(800)]),
        ),
    ]
