# Generated by Django 4.2.2 on 2023-07-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_postinfo_height_postinfo_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='postinfo',
            name='width',
        ),
    ]
